#+TITLE: NT Government Housing Maintenance Recording app for the Walangeri Ngumpinku Aboriginal Corporation
#+AUTHOR: Anthony Beckett
#+AUTHOR: Aakarsh Singh

** Description

This is a React Native application designed with Android devices in mind. It was built at the behest of the [[https://walangeri.com.au][Walangeri Ngumpinku Aboriginal Corporation]] for [[https://unisa.edu.au][the University of South Australia's]] (UniSA) ICT Capstone Project.

The Walangeri Corporation approached UniSA in the hope of solving an issue they regularly ran into. Namely, issues with recording and keeping track of housing maintenance tasks. This application seeks to be a solution to this problem.

It does this by essentially presenting a form for users to fill out when reporting faults. The form consists of:

- An image one may attach or take from within the application of the reported fault.
- A name one may attach for the fault
- Lot/Address information
- Type of job (/carpentry, etc/)
- Urgency of the job
- Any additional notes

** How to use
- First, please clone the backend code at [[https://github.com/aakarshsingh1217/Walangeri-Backend]]
- Then, clone this frontend code
- Download Android Studio and use the Medium_Phone_API_TiramisuPrivacySandbox and start running the emulator
- Run an npm install command in the roots of both the frontend and backend code
- run the 'npm run dev' command in the backend code root
- run the 'npm start' command in the frontend code root, then enter the character 'a' to have expo build the app and run on the emulator

** Rights

All rights belong to the Walangeri Ngumpinku Aboriginal Corporation. Permission has been sought and approved for making this repository public, but it remains proprietary software owned by the Walangeri Ngumpinku Aboriginal Corporation. Any use of this software by third-parties must be approved by the aforementioned corporation.

** Credit

Designed and developed by UniSA students:

Anthony Beckett (Project Manager; Software Engineer)
- LinkedIn: [[https://linkedin.com/in/anthony-beckett]]

Aakarsh Singh (Full-Stack Developer)
- LinkedIn: [[https://www.linkedin.com/in/aakarshsingh678/]]